name: bibit_technical_test

sdkPath: .fvm/flutter_sdk

packages:
  - alarm/*
  - analog_clock/*
  - application/*
  - notification/*
  
scripts:
  get:
    run: melos exec -- flutter pub get 
    description: |
      Run `flutter pub get` in all packages.
      
  analyze: 
    run: melos exec -- flutter analyze
    description: |
      Run `flutter analyze` in all packages.

  format:
    run: melos exec -- flutter format --set-exit-if-changed .
    description: | 
      Run `flutter format` in all packages.

  build_runner:
    run: melos exec --depends-on="build_runner" -- flutter pub run build_runner build --delete-conflicting-outputs
    description: |
      Run `build_runner` build command in all packages that has a dependency on `build_runner`.
