import 'package:floor/floor.dart';

/// Representation of alarm that can be created by the user.
@Entity(tableName: 'alarms', indices: [
  Index(value: ['scheduled_for']),
])
class AlarmModel {
  AlarmModel({
    this.id,
    required this.scheduledFor,
    this.secondElapsed,
  });

  /// nullable because it will be generated by SQLite.
  /// set to [null] when inserting a new record.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  /// when was this alarm scheduled for.
  @ColumnInfo(name: 'scheduled_for')
  final DateTime scheduledFor;

  /// seconds elapsed before user tapped on the alarm notification.
  /// if [null], it means it's not yet tapped or opened.
  @ColumnInfo(name: 'seconds_elapsed')
  final int? secondElapsed;
}
